### ISSUE TITLE
TypeError: Endpoint URL must start with `http:` or `https:`.

### ISSUE THREAD

**Issue by Ding-Fan** [helium/maker-starter-app#80]
The error message is 

```sh
2023-05-18 16:33:25.080  8190-8286  ReactNativeJS           com.maker.makerapp                   E  TypeError: Endpoint URL must start with `http:` or `https:`.
                                                                                                
This error is located at:
      in s
      in P
      in n
      in l
      in f
      in RCTView
      in Unknown
      in RCTView
      in Unknown
      in y, js engine: hermes
2023-05-18 16:33:25.084  8190-8286  ReactNativeJS           com.maker.makerapp                   E  TypeError: Endpoint URL must start with `http:` or `https:`.
                                                                                                    
   This error is located at:
      in s
      in P
      in n
      in l
      in f
      in RCTView
      in Unknown
      in RCTView
      in Unknown
      in y, js engine: hermes
2023-05-18 16:33:25.091  8190-8287  unknown:ReactNative     com.maker.makerapp                   E  TypeError: Endpoint URL must start with `http:` or `https:`.
                                                                                                    
   This error is located at:
      in s
      in P
      in n
      in l
      in f
      in RCTView
      in Unknown
      in RCTView
      in Unknown
      in y, js engine: hermes, stack:
   Qe@1710:54527
   e@1710:72702
   anonymous@2196:2632
   useMemo@49:50284
   anonymous@132:6129
   M@2196:2590
   s@2421:2013
   Cr@49:43504
   Sa@49:95925
   vi@49:86899
   gi@49:86801
   hi@49:86566
   oi@49:83486
   pt@49:27332
   Za@49:79770
   Hi@49:95299
   anonymous@49:101549
   anonymous@335:689
   run@332:741
   runApplication@332:1812
   value@34:3797
   anonymous@34:673
   value@34:2503
   value@34:645
2023-05-18 16:33:25.098  8190-8287  unknown:ReactNative     com.maker.makerapp                   E  Exception in native call
                                                                                                    com.facebook.react.common.JavascriptException: TypeError: Endpoint URL must start with `http:` or `https:`.
                                                                                                    
   This error is located at:
      in s
      in P
      in n
      in l
      in f
      in RCTView
      in Unknown
      in RCTView
      in Unknown
      in y, js engine: hermes, stack:
   Qe@1710:54527
   e@1710:72702
   anonymous@2196:2632
   useMemo@49:50284
   anonymous@132:6129
   M@2196:2590
   s@2421:2013
   Cr@49:43504
   Sa@49:95925
   vi@49:86899
   gi@49:86801
   hi@49:86566
   oi@49:83486
   pt@49:27332
   Za@49:79770
   Hi@49:95299
   anonymous@49:101549
   anonymous@335:689
   run@332:741
   runApplication@332:1812
   value@34:3797
   anonymous@34:673
   value@34:2503
   value@34:645
   
      at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
      at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
      at com.facebook.jni.NativeRunnable.run(Native Method)
      at android.os.Handler.handleCallback(Handler.java:938)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
      at android.os.Looper.loop(Looper.java:232)
      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
      at java.lang.Thread.run(Thread.java:923)
```

**Comment by Ding-Fan** [comment]
fixed by add correct devnet url to .env and remove gradle cache
